name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 890742580558.dkr.ecr.ap-southeast-1.amazonaws.com

    - name: Build, Tag, and Push Docker image
      run: |
        docker build -t my-node-app ./app
        docker tag my-node-app:latest 890742580558.dkr.ecr.ap-southeast-1.amazonaws.com/my-node-app:latest
        docker push 890742580558.dkr.ecr.ap-southeast-1.amazonaws.com/my-node-app:latest

    - name: Deploy to EC2 over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull 890742580558.dkr.ecr.ap-southeast-1.amazonaws.com/my-node-app:latest
          docker stop app || true && docker rm app || true
          docker run -d -p 80:3000 --name app 890742580558.dkr.ecr.ap-southeast-1.amazonaws.com/my-node-app:latest

